repoURL: "https://github.com/morten-olsen/homelab-apps"
targetRevision: "main"
path: "apps/charts"
exclude: "*.disabled"
project: "apps"
globals:
  environment: prod
  domain: olsen.cloud
  timezone: Europe/Amsterdam
  istio:
    gateway: shared/private
    gateways:
      private: shared/private
      public: shared/public

