apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-valkey"
  labels:
    app: "{{ .Release.Name }}-valkey"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: tcp
  selector:
    app: "{{ .Release.Name }}-valkey"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-ml"
  labels:
    app: "{{ .Release.Name }}-ml"
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app: "{{ .Release.Name }}-ml"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}-server"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app: "{{ .Release.Name }}-server"
