apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Release.Name }}-woodpecker"

  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://woodpecker-ci.org/
    chart: woodpecker
    targetRevision: 3.4.2
    helm:
      releaseName: woodpecker
      values: |
        server:
          extraSecretNamesForEnvFrom:
            - {{ .Release.Name }}-woodpecker-secret
          env:
            WOODPECKER_HOST: "https://woodpecker.{{ .Values.globals.domain }}"
            WOODPECKER_FORGEJO: "true"
            WOODPECKER_FORGEJO_URL: "https://{{ .Values.subdomain }}.{{ .Values.globals.domain }}"
            WOODPECKER_FORGEJO_CLIENT: "b3b42b15-3a60-4683-b548-b78fb3d82869"
            WOODPECKER_FORGEJO_SECRET: "gto_xinhg5w3awf3moi64a4mqwzsbzv6mbnvb3ibyo6s7oo6d7j4n7da"
            WOODPECKER_ADMIN: morten-olsen
            WOODPECKER_BACKEND_K8S_STORAGE_CLASS: "{{ .Values.globals.environment }}"
            WOODPECKER_BACKEND_K8S_STORAGE_RWX: "false"
            WOODPECKER_PLUGINS_PRIVILEGED: plugins/docker
          ingress:
            enabled: false
          persistentVolume:
            enabled: true
            accessModes:
              - ReadWriteOnce
            size: 10Gi
            storageClass: "prod"
        agent:
          extraSecretNamesForEnvFrom:
            - {{ .Release.Name }}-woodpecker-secret
          env:
            WOODPECKER_SERVER: "woodpecker-server:9000"
          persistence:
            storageClass: "{{ .Values.globals.environment }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
