apiVersion: homelab.mortenolsen.pro/v1
kind: GenerateSecret
metadata:
  name: "{{ .Release.Name }}-woodpecker-secret"
spec:
  fields:
    - name: WOODPECKER_AGENT_SECRET
      encoding: hex
      length: 64
