host: 192.168.20.106
shares:
  movies:
    path: /mnt/HDD/Movies
  tvshows:
    path: /mnt/HDD/TV-Shows
  music:
    path: /mnt/HDD/Music
  books:
    path: /mnt/HDD/Books
  podcasts:
    path: /mnt/HDD/Podcasts
  pictures:
    path: /mnt/HDD/Pictures
  backups:
    path: /mnt/HDD/Backups
  youtube:
    path: /mnt/HDD/Youtube
  misc:
    path: /mnt/HDD/Misc
  kidsmusic:
    path: /mnt/HDD/Kids/Music
  images:
    path: /mnt/HDD/images
  kidsyoutube:
    path: /mnt/HDD/Kids/YouTube
