frontend:
  subdomain: penpot
  image:
    repository: penpotapp/frontend
    tag: 2.12.1@sha256:e6f20a1ce5224e3cec4bbdb63892319bcf7e751c95b4baff8b1343e3fac668d6
    pullPolicy: IfNotPresent
backend:
  image:
    repository: penpotapp/backend
    tag: 2.12.1@sha256:8400aeccabc564c2c23ef5ebbc087d6382044f4ffa45e2d7db260a73c6eac398
    pullPolicy: IfNotPresent
exporter:
  image:
    repository: penpotapp/exporter
    tag: 2.12.1@sha256:a245ec857c2c5cc7e8702309134312d459af086a2bd2e07983d5cf1d3f30e841
    pullPolicy: IfNotPresent
valkey:
  image:
    repository: valkey/valkey
    tag: 9.0@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    pullPolicy: IfNotPresent
