frontend:
  subdomain: penpot
  image:
    repository: penpotapp/frontend
    tag: 2.13.2@sha256:d98e7c9ddb55617f7628845653aa20efe4646b62b1727e192bfb61013b56206a
    pullPolicy: IfNotPresent
backend:
  image:
    repository: penpotapp/backend
    tag: 2.13.2@sha256:d2fd58465adc02e90db6f220ed012e3e77135b551baa1b2b5a6a155060849ea3
    pullPolicy: IfNotPresent
exporter:
  image:
    repository: penpotapp/exporter
    tag: 2.13.2@sha256:91dace40fd829bfeeb550680da7ece22203c215e57e558398d87c589422c5574
    pullPolicy: IfNotPresent
valkey:
  image:
    repository: valkey/valkey
    tag: 9.0@sha256:930b41430fb727f533c5982fe509b6f04233e26d0f7354e04de4b0d5c706e44e
    pullPolicy: IfNotPresent
