frontend:
  subdomain: penpot
  image:
    repository: penpotapp/frontend
    tag: 2.12.0@sha256:9080c53cbcab41572551adb66f288f4cfa8cbf51a19488248dd9ea45449b5a77
    pullPolicy: IfNotPresent
backend:
  image:
    repository: penpotapp/backend
    tag: 2.12.0@sha256:ba36dd0431cfbacfbbef10e6413a7ff0a33c333012f78dd3c921a98e2436f60f
    pullPolicy: IfNotPresent
exporter:
  image:
    repository: penpotapp/exporter
    tag: 2.12.0@sha256:3875a0522a898855fe7ad6983b66739140dc8129a06da6922489a1e785087bcf
    pullPolicy: IfNotPresent
valkey:
  image:
    repository: valkey/valkey
    tag: 9.0@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    pullPolicy: IfNotPresent
