frontend:
  subdomain: penpot
  image:
    repository: penpotapp/frontend
    tag: 2.13.0@sha256:145aee7789906a80b140b89257cc7910ea62d7cba8c6bbeb85142e6fe83f5094
    pullPolicy: IfNotPresent
backend:
  image:
    repository: penpotapp/backend
    tag: 2.13.0@sha256:723f0ca237faf19c84c5396d1cbcca27938884905cf0c194410b7cb015fb12dc
    pullPolicy: IfNotPresent
exporter:
  image:
    repository: penpotapp/exporter
    tag: 2.13.0@sha256:f570253d5e4726793f222c8c3e1c91eca180d0f44df9203180c1baa131272e76
    pullPolicy: IfNotPresent
valkey:
  image:
    repository: valkey/valkey
    tag: 9.0@sha256:930b41430fb727f533c5982fe509b6f04233e26d0f7354e04de4b0d5c706e44e
    pullPolicy: IfNotPresent
