{{ include "common.deployment" . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-runner"
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-runner"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-runner"
    spec:
      containers:
        - name: "{{ .Release.Name }}-runner"
          image: "{{ .Values.runner.image.repository }}:{{ .Values.runner.image.tag }}"
          imagePullPolicy: "{{ .Values.runner.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 5680
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          env:
            - name: TZ
              value: "{{ .Values.globals.timezone }}"
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secret"
                  key: password
            - name: N8N_RUNNERS_TASK_BROKER_URI
              value: 'http://{{ .Release.Name }}-broker:80'
          volumeMounts:
            - mountPath: /etc/n8n-task-runners.json
              name: config
              subPath: n8n-task-runners.json
      volumes:
        - name: config
          configMap:
            name: "{{ .Release.Name }}-runner-config"
