apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-valkey"
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app: "{{ .Release.Name }}-valkey"
spec:
  ports:
    - port: 6379
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app: "{{ .Release.Name }}-valkey"
