{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-oidc-providers
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  providers: ""
{{- end }}
