{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.fullname" . }}-oidc-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- end }}
