apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: prod
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None
  type: ClusterIP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: truenas
  namespace: prod
  labels:
    kubernetes.io/service-name: truenas
  annotations:
    argocd.argoproj.io/sync-options: Prune=false;ServerSideApply=true
addressType: IPv4
endpoints:
  - addresses:
      - "192.168.20.106"
ports:
  - port: 80
    protocol: TCP
