apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-operator
  namespace: argocd
spec:
  project: foundation
  source:
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 7.0.2
    chart: falco
    helm:
      releaseName: falco
  destination:
    server: https://kubernetes.default.svc
    namespace: foundation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
