apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: foundation
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 79.11.0
    chart: kube-prometheus-stack
    helm:
      releaseName: kps
      values: |
        prometheusr:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "{{ .Values.globals.storageClass }}" # Replace with your StorageClass
                  accessModes: ["ReadWriteOnce"]
        alertmanager:
          name: alerts
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: "{{ .Values.globals.storageClass }}" # Replace with your StorageClass
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: foundation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
