apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-operator
  namespace: argocd
spec:
  project: foundation
  source:
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 3.1.0
    chart: kyverno
    helm:
      releaseName: kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: foundation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
