apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nuclei-operator
  namespace: argocd
spec:
  project: foundation
  source:
    repoURL: https://morten-olsen.github.io/homelab-nuclei-operator
    targetRevision: 0.2.4
    chart: nuclei-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: foundation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
