---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: foundation
    server: https://kubernetes.default.svc
  project: foundation
  source:
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 2.2.5
    chart: reloader
    helm: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
