{{- if .Values.oidc.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.fullname" . }}-oidc-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.fullname" . }}-oidc-config
subjects:
- kind: ServiceAccount
  name: {{ include "common.fullname" . }}-oidc-config
  namespace: {{ .Release.Namespace }}
{{- end }}
