{{- if .Values.oidc.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.fullname" . }}-oidc-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
  - {{ .Release.Name }}-oidc-credentials
  - {{ include "common.fullname" . }}-oidc-providers
  verbs: ["get", "create", "update", "patch"]
{{- end }}
