apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-server"
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-server"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-server"
    spec:
      containers:
        - name: "{{ .Release.Name }}-server"
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-pg-connection"
                  key: url
            - name: DB_VECTOR_EXTENSION
              value: pgvector
            - name: REDIS_HOST
              value: "{{ .Release.name }}-valkey.{{ .Release.Namespace }}.svc.cluster.local"
            - name: IMMICH_PORT
              value: "3003"
          ports:
            - name: http
              containerPort: 3003 
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-ml"
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-ml"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-ml"
    spec:
      containers:
        - name: "{{ .Release.Name }}-ml"
          image: "{{ .Values.ml.image.repository }}:{{ .Values.ml.image.tag }}"
          imagePullPolicy: "{{ .Values.ml.image.pullPolicy }}"
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-pg-connection"
                  key: url
            # - name: DB_VECTOR_EXTENSION
            #   value: pgvector
            - name: REDIS_HOST
              value: "{{ .Release.name }}-valkey"
            - name: IMMICH_PORT
              value: "3003"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-valkey"
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-valkey"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-valkey"
    spec:
      containers:
        - name: "{{ .Release.Name }}-valkey"
          image: "{{ .Values.valkey.image.repository }}:{{ .Values.valkey.image.tag }}"
          imagePullPolicy: "{{ .Values.valkey.image.pullPolicy }}"
          ports:
            - name: tcp
              containerPort: 6379
              protocol: TCP

