apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-es"
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app: "{{ .Release.Name }}-es"
spec:
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "{{ .Release.Name }}-es"
