image:
  repository: ghcr.io/gouryella/drip
  tag: latest@sha256:440bcfd7eb75bf0b337d60346e44ae9e5be803e2504697ea7aa1b4f5fce568b9
  pullPolicy: IfNotPresent
subdomain: drip

service:
  port: 443
  tcpPortMin: 20000
  tcpPortMax: 20100

resources:
  limits:
    cpu: 1
    memory: 512Mi

healthcheck:
  test:
    - wget
    - --no-verbose
    - --tries=1
    - --spider
    - http://localhost:443/health
  interval: 30s
  timeout: 3s
  retries: 3
  startPeriod: 10s
