image:
  repository: ghcr.io/gouryella/drip
  tag: latest@sha256:55c0812767287f5fabc0b308c98705038a4ec7f88af4b59548b1d095c8ff322a
  pullPolicy: IfNotPresent
subdomain: drip

service:
  port: 443
  tcpPortMin: 20000
  tcpPortMax: 20100

resources:
  limits:
    cpu: 1
    memory: 512Mi

healthcheck:
  test:
    - wget
    - --no-verbose
    - --tries=1
    - --spider
    - http://localhost:443/health
  interval: 30s
  timeout: 3s
  retries: 3
  startPeriod: 10s
