apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}-public"
  namespace: "{{ .Release.Namespace }}"
spec:
  gateways:
    - "{{ .Values.globals.istio.gateways.public }}"
    - mesh
  hosts:
    - "{{ .Values.subdomain }}.{{ .Values.globals.domain }}"
    - mesh
  http:
    - route:
        - destination:
            host: "{{ .Release.Name }}"
            port:
              number: 80

