apiVersion: homelab.mortenolsen.pro/v1
kind: OidcClient
metadata:
  name: "{{ .Release.Name }}"
spec:
  environment: "{{ .Values.globals.environment }}"
  redirectUris:
    - path: /auth/openid/oidc
      subdomain: "{{ .Values.subdomain }}"
      matchingMode: strict
